---
- name: Check Application and Database Status
  hosts: all
  tasks:
    - name: Check whether application and database are running
      script: /home/ansible/dev/appcheck.sh
      args:
        executable: /bin/bash
      ignore_errors: true
      register: application_process_check
