---
- name: Reboot System Failure
  hosts: all
  tasks:
    - name: Fail if rebooting system fails
      fail:
        msg: "Failed to reboot system on {{ inventory_hostname }}"
      when: reboot_started.failed
